<a href="https://colab.research.google.com/github/Kim-Hyerin/pdm06/blob/master/numpy_2_array_pdm06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [ ]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# step through rows
for row in range(data.shape[0]):
	print(data[row,:])

[1 2 3]
[4 5 6]


## Print columns

In [ ]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col])

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [ ]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [ ]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis=0)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [ ]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis=1)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [도전하기]

- 3차원 배열을 리스트로부터 만드시오.

In [ ]:
# Make 3d-array in numpy
'''
data = [[1,2,3], [4,5,6]]
'''

In [ ]:
data3d = [[1,2,3], [4,5,6], [7,8,9]]

In [ ]:
data3d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
from numpy import asarray
data3d = asarray(data3d)

In [ ]:
data3d.ndim  # 2차원

2

3차원배열 : n X m X I , (n,m,I)

In [ ]:
data3d = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
data3d = asarray(data3d)

In [ ]:
data3d.ndim # data3d의 차원

3

In [ ]:
data3d.shape # 3면 2행 3열

(3, 2, 3)

In [ ]:
data3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
data3d.sum(axis=0) # x축을 기준으로 여러 행을 한 개로 합치는 과정

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
data3d.sum(axis=1) # y축을 기준으로 행 별로 존재하는 열들의 값을 합쳐 1개로 축소하는 과정

array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]])

In [ ]:
data3d.sum(axis=2) # z축을 기준으로 열의 depth가 가진 값을 축소하는 과정

array([[ 6, 15],
       [ 6, 15],
       [ 6, 15]])

In [ ]:
data3d.sum(axis=(0,1)) # 0은 열, 1은 행, 2는 첫번째와 두번째의 행을 비교

array([15, 21, 27])

In [ ]:
data3d.sum(axis=(0,2))

array([18, 45])

In [ ]:
data3d.sum(axis=(1,2))

array([21, 21, 21])

### 위의 3차원 배열에 대한 계산 결과를 간단히 주석으로 설명해보세요.